// Structured AI Mentor response types for startup idea generation
// DeepSeek V4 Flash returns structured JSON matching these types

/**
 * Possible next actions a user can take for a startup idea.
 */
export type StartupIdeaAction =
  | 'validate'
  | 'find_cofounder'
  | 'market_research'
  | 'build_mvp'
  | 'competitor_analysis'
  | 'fundraising'
  | 'team_building'
  | 'customer_interviews'

/**
 * Niche scoring breakdown for a startup idea.
 * Predicts viability and fit across multiple dimensions.
 */
export interface NicheScore {
  /** Overall niche score 0-100 */
  overall: number
  /** Market fit score 0-100 */
  market_fit: number
  /** Skill complementarity score 0-100 */
  skill_match: number
  /** Feasibility / doability score 0-100 */
  feasibility: number
  /** Uniqueness / differentiation score 0-100 */
  uniqueness: number
}

/**
 * A single startup idea card generated by the AI Mentor.
 */
export interface StartupIdea {
  readonly id: number
  /** Short, catchy startup name */
  title: string
  /** One-line value proposition */
  tagline: string
  /** The problem it solves (1-2 sentences) */
  problem: string
  /** How the product solves the problem */
  solution: string
  /** Who the product serves */
  target_market: string
  /** Why this matches the user's skills and interests */
  why_you: string
  /** Collaboration-specific: why both people should work on this together */
  why_you_two?: string
  /** Implementation difficulty level */
  difficulty: 'easy' | 'moderate' | 'hard'
  /** Predicted niche viability score with breakdown */
  niche_score?: NicheScore
  /** Suggested next actions for the user */
  actions: StartupIdeaAction[]
}

/**
 * A categorized collection of related startup ideas.
 */
export interface StartupIdeaCollection {
  /** Category label e.g. 'AI-powered tools', 'Developer tools' */
  category: string
  /** 2-3 ideas in this category */
  ideas: StartupIdea[]
}

/**
 * Top-level response wrapper returned by the AI Mentor.
 * `message` contains human-readable intro text (up to ~500 chars).
 */
export interface AIStructuredResponse {
  /** Human-readable intro text, up to ~500 characters */
  message: string
  /** Flat list of startup ideas (alternative to collections) */
  ideas?: StartupIdea[]
  /** Ideas grouped by category (alternative to flat ideas) */
  collections?: StartupIdeaCollection[]
  /** Clickable follow-up prompts, 3-5 items */
  suggestions: string[]
  /** How well the generated ideas match the user's profile */
  profile_match?: {
    /** Which user skills were leveraged in these ideas */
    skills_used: string[]
    /** Which user interests are addressed */
    interests_addressed: string[]
    /** Overall fit score, 0-100 */
    match_score: number
  }
}

/**
 * Enhanced chat message for the frontend.
 * `content` is raw text (user) or JSON string (assistant).
 * `structured` holds the parsed AI response when available.
 * `created_at` is ISO 8601 format.
 */
export interface ChatMessage {
  readonly id: string
  role: 'user' | 'assistant'
  /** Raw text for users, JSON string for assistant responses */
  content: string
  /** Parsed structured data (assistant messages only) */
  structured?: AIStructuredResponse
  /** ISO 8601 timestamp */
  created_at: string
  is_streaming?: boolean
}

/**
 * Runtime type guard that validates an unknown value conforms
 * to AIStructuredResponse. Performs exhaustive field checking.
 */
export function isAIStructuredResponse(data: unknown): data is AIStructuredResponse {
  if (data === null || typeof data !== 'object') return false

  const obj = data as Record<string, unknown>

  if (typeof obj.message !== 'string') return false
  if (!Array.isArray(obj.suggestions)) return false
  if (obj.suggestions.some(s => typeof s !== 'string')) return false

  if (obj.ideas !== undefined) {
    if (!Array.isArray(obj.ideas)) return false
    for (const idea of obj.ideas) {
      if (typeof idea !== 'object' || idea === null) return false
      const i = idea as Record<string, unknown>
      if (typeof i.title !== 'string') return false
      if (typeof i.tagline !== 'string') return false
      if (typeof i.problem !== 'string') return false
      if (typeof i.solution !== 'string') return false
      if (typeof i.target_market !== 'string') return false
      if (typeof i.why_you !== 'string') return false
      if (!['easy', 'moderate', 'hard'].includes(i.difficulty as string)) return false
      if (!Array.isArray(i.actions)) return false
      const validActions = [
        'validate', 'find_cofounder', 'market_research', 'build_mvp',
        'competitor_analysis', 'fundraising', 'team_building', 'customer_interviews',
      ]
      for (const a of i.actions) {
        if (!validActions.includes(a as string)) return false
      }
      // niche_score is optional but if present must have valid shape
      if (i.niche_score !== undefined) {
        if (typeof i.niche_score !== 'object' || i.niche_score === null) return false
        const ns = i.niche_score as Record<string, unknown>
        if (typeof ns.overall !== 'number') return false
        if (typeof ns.market_fit !== 'number') return false
        if (typeof ns.skill_match !== 'number') return false
        if (typeof ns.feasibility !== 'number') return false
        if (typeof ns.uniqueness !== 'number') return false
      }
    }
  }

  if (obj.collections !== undefined) {
    if (!Array.isArray(obj.collections)) return false
    for (const col of obj.collections) {
      if (typeof col !== 'object' || col === null) return false
      const c = col as Record<string, unknown>
      if (typeof c.category !== 'string') return false
      if (!Array.isArray(c.ideas)) return false
      for (const idea of c.ideas) {
        if (typeof idea !== 'object' || idea === null) return false
        const i = idea as Record<string, unknown>
        if (typeof i.title !== 'string') return false
        if (typeof i.tagline !== 'string') return false
        if (typeof i.problem !== 'string') return false
        if (typeof i.solution !== 'string') return false
        if (typeof i.target_market !== 'string') return false
        if (typeof i.why_you !== 'string') return false
        if (!['easy', 'moderate', 'hard'].includes(i.difficulty as string)) return false
        if (!Array.isArray(i.actions)) return false
      }
    }
  }

  if (obj.profile_match !== undefined) {
    if (typeof obj.profile_match !== 'object' || obj.profile_match === null) return false
    const pm = obj.profile_match as Record<string, unknown>
    if (!Array.isArray(pm.skills_used)) return false
    if (pm.skills_used.some(s => typeof s !== 'string')) return false
    if (!Array.isArray(pm.interests_addressed)) return false
    if (pm.interests_addressed.some(s => typeof s !== 'string')) return false
    if (typeof pm.match_score !== 'number') return false
  }

  return true
}

/**
 * Server-Sent Event payload for streaming AI responses.
 * `type` indicates the event phase:
 * - 'content': streaming text chunk
 * - 'structured': final structured payload ready
 * - 'done': stream complete
 * - 'error': error occurred
 */
export interface StreamEvent {
  type: 'content' | 'structured' | 'done' | 'error'
  /** Text chunk for 'content' events */
  content?: string
  /** Final structured payload for 'structured' events */
  structured?: AIStructuredResponse
  /** Error message for 'error' events */
  error?: string
}
