"""
Skill Categories for Complementary Matching
Maps every known skill to a broad category so the match algorithm can determine
whether two users have similar skills (same category) or complementary skills
(different categories).

A frontend developer (react → "frontend") matched with a backend developer
(python → "backend") scores higher on complementarity than two frontend devs.
"""

SKILL_CATEGORIES: dict[str, str] = {
    # ── Frontend Development ──────────────────────────────────────────────
    "react": "frontend",
    "vue": "frontend",
    "angular": "frontend",
    "svelte": "frontend",
    "nextjs": "frontend",
    "nuxtjs": "frontend",
    "remix": "frontend",
    "astro": "frontend",
    "html": "frontend",
    "html5": "frontend",
    "css": "frontend",
    "css3": "frontend",
    "tailwind": "frontend",
    "bootstrap": "frontend",
    "sass": "frontend",
    "less": "frontend",
    "styled-components": "frontend",
    "emotion": "frontend",
    "webpack": "frontend",
    "vite": "frontend",
    "javascript": "frontend",
    "typescript": "frontend",
    "jquery": "frontend",
    "redux": "frontend",
    "zustand": "frontend",
    "graphql": "frontend",
    "apollo": "frontend",
    "pwa": "frontend",
    "web-components": "frontend",
    "responsive-design": "frontend",
    "cross-browser": "frontend",
    "web-performance": "frontend",
    "a11y": "frontend",
    # ── Backend Development ───────────────────────────────────────────────
    "nodejs": "backend",
    "node.js": "backend",
    "express": "backend",
    "fastify": "backend",
    "nestjs": "backend",
    "django": "backend",
    "flask": "backend",
    "fastapi": "backend",
    "spring": "backend",
    "spring-boot": "backend",
    "laravel": "backend",
    "rails": "backend",
    "ruby-on-rails": "backend",
    "aspnet": "backend",
    "dotnet": "backend",
    "go": "backend",
    "golang": "backend",
    "rust": "backend",
    "java": "backend",
    "kotlin": "backend",
    "php": "backend",
    "csharp": "backend",
    "python": "backend",
    "ruby": "backend",
    "scala": "backend",
    "elixir": "backend",
    "c": "backend",
    "cpp": "backend",
    "rest": "backend",
    "api": "backend",
    "grpc": "backend",
    "websocket": "backend",
    "microservices": "backend",
    "serverless": "backend",
    "rabbitmq": "backend",
    "kafka": "backend",
    "celery": "backend",
    "backend-architecture": "backend",
    # ── Database ──────────────────────────────────────────────────────────
    "sql": "database",
    "postgresql": "database",
    "postgres": "database",
    "mysql": "database",
    "mariadb": "database",
    "sqlite": "database",
    "mongodb": "database",
    "cassandra": "database",
    "redis": "database",
    "elasticsearch": "database",
    "dynamodb": "database",
    "bigquery": "database",
    "snowflake": "database",
    "cockroachdb": "database",
    "supabase": "database",
    "prisma": "database",
    "drizzle": "database",
    "typeorm": "database",
    "sqlalchemy": "database",
    "database-design": "database",
    "query-optimization": "database",
    "indexing": "database",
    "sharding": "database",
    "migration": "database",
    "orm": "database",
    "nosql": "database",
    # ── DevOps & Infrastructure ───────────────────────────────────────────
    "docker": "devops",
    "kubernetes": "devops",
    "k8s": "devops",
    "terraform": "devops",
    "ansible": "devops",
    "jenkins": "devops",
    "github-actions": "devops",
    "gitlab-ci": "devops",
    "circleci": "devops",
    "argocd": "devops",
    "helm": "devops",
    "prometheus": "devops",
    "grafana": "devops",
    "datadog": "devops",
    "sentry": "devops",
    "elk": "devops",
    "istio": "devops",
    "consul": "devops",
    "vault": "devops",
    "ci/cd": "devops",
    "deployment": "devops",
    "sre": "devops",
    "monitoring": "devops",
    "alerting": "devops",
    "opentelemetry": "devops",
    "git": "devops",
    "linux": "devops",
    "bash": "devops",
    "shell": "devops",
    # ── Cloud ─────────────────────────────────────────────────────────────
    "aws": "cloud",
    "amazon-web-services": "cloud",
    "azure": "cloud",
    "google-cloud": "cloud",
    "gcp": "cloud",
    "digital-ocean": "cloud",
    "heroku": "cloud",
    "vercel": "cloud",
    "netlify": "cloud",
    "cloudflare": "cloud",
    "cloud-architecture": "cloud",
    "multi-cloud": "cloud",
    "hybrid-cloud": "cloud",
    # ── AI & Machine Learning ─────────────────────────────────────────────
    "machine-learning": "ai-ml",
    "deep-learning": "ai-ml",
    "neural-networks": "ai-ml",
    "tensorflow": "ai-ml",
    "pytorch": "ai-ml",
    "keras": "ai-ml",
    "scikit-learn": "ai-ml",
    "pandas": "ai-ml",
    "numpy": "ai-ml",
    "nlp": "ai-ml",
    "natural-language-processing": "ai-ml",
    "computer-vision": "ai-ml",
    "llm": "ai-ml",
    "large-language-model": "ai-ml",
    "openai": "ai-ml",
    "langchain": "ai-ml",
    "huggingface": "ai-ml",
    "transformers": "ai-ml",
    "rag": "ai-ml",
    "retrieval-augmented-generation": "ai-ml",
    "prompt-engineering": "ai-ml",
    "fine-tuning": "ai-ml",
    "embeddings": "ai-ml",
    "vector-database": "ai-ml",
    "data-science": "ai-ml",
    "mlops": "ai-ml",
    "generative-ai": "ai-ml",
    "stable-diffusion": "ai-ml",
    "recommendation-system": "ai-ml",
    "reinforcement-learning": "ai-ml",
    "anomaly-detection": "ai-ml",
    "classification": "ai-ml",
    "regression": "ai-ml",
    "clustering": "ai-ml",
    "feature-engineering": "ai-ml",
    "model-deployment": "ai-ml",
    "ai-ethics": "ai-ml",
    # ── Cybersecurity ─────────────────────────────────────────────────────
    "cybersecurity": "security",
    "network-security": "security",
    "application-security": "security",
    "penetration-testing": "security",
    "ethical-hacking": "security",
    "vulnerability-assessment": "security",
    "incident-response": "security",
    "forensics": "security",
    "cryptography": "security",
    "risk-management": "security",
    "compliance": "security",
    "soc2": "security",
    "gdpr": "security",
    "hipaa": "security",
    "security-audit": "security",
    "threat-hunting": "security",
    "malware-analysis": "security",
    "zero-trust": "security",
    "identity-management": "security",
    "access-control": "security",
    "oauth": "security",
    "saml": "security",
    "jwt": "security",
    "sso": "security",
    "mfa": "security",
    "2fa": "security",
    # ── Mobile ────────────────────────────────────────────────────────────
    "ios": "mobile",
    "swift": "mobile",
    "swiftui": "mobile",
    "objective-c": "mobile",
    "android": "mobile",
    "kotlin-mobile": "mobile",
    "jetpack-compose": "mobile",
    "react-native": "mobile",
    "flutter": "mobile",
    "dart": "mobile",
    "mobile-ui": "mobile",
    "mobile-ux": "mobile",
    "push-notifications": "mobile",
    # ── Design ────────────────────────────────────────────────────────────
    "ui-design": "design",
    "ux-design": "design",
    "visual-design": "design",
    "product-design": "design",
    "interaction-design": "design",
    "service-design": "design",
    "design-system": "design",
    "figma": "design",
    "sketch": "design",
    "adobe-xd": "design",
    "photoshop": "design",
    "illustrator": "design",
    "wireframing": "design",
    "prototyping": "design",
    "user-research": "design",
    "usability": "design",
    "information-architecture": "design",
    "user-flows": "design",
    "color-theory": "design",
    "typography": "design",
    "design-thinking": "design",
    "motion-design": "design",
    # ── Creative & Content ────────────────────────────────────────────────
    "illustration": "creative",
    "drawing": "creative",
    "digital-art": "creative",
    "3d-modeling": "creative",
    "blender": "creative",
    "animation": "creative",
    "motion-graphics": "creative",
    "video-editing": "creative",
    "photography": "creative",
    "videography": "creative",
    "film-making": "creative",
    "storytelling": "creative",
    "content-creation": "creative",
    "copywriting": "creative",
    "creative-writing": "creative",
    "technical-writing": "creative",
    "content-writing": "creative",
    "brand-identity": "creative",
    "logo-design": "creative",
    "music-production": "creative",
    "sound-design": "creative",
    "podcasting": "creative",
    # ── Business & Management ─────────────────────────────────────────────
    "product-management": "business",
    "project-management": "business",
    "program-management": "business",
    "product-strategy": "business",
    "product-roadmap": "business",
    "agile": "business",
    "scrum": "business",
    "kanban": "business",
    "business-strategy": "business",
    "strategic-planning": "business",
    "business-development": "business",
    "business-analysis": "business",
    "management-consulting": "business",
    "consulting": "business",
    "operations-management": "business",
    "change-management": "business",
    "vendor-management": "business",
    "procurement": "business",
    "supply-chain": "business",
    "negotiation": "business",
    "contract-management": "business",
    "executive-leadership": "business",
    "entrepreneurship": "business",
    "startup": "business",
    "venture-building": "business",
    "innovation": "business",
    "leadership": "business",
    "public-speaking": "business",
    "presentation": "business",
    # ── Marketing ─────────────────────────────────────────────────────────
    "digital-marketing": "marketing",
    "content-marketing": "marketing",
    "social-media-marketing": "marketing",
    "email-marketing": "marketing",
    "influencer-marketing": "marketing",
    "affiliate-marketing": "marketing",
    "growth-hacking": "marketing",
    "seo": "marketing",
    "search-engine-optimization": "marketing",
    "sem": "marketing",
    "paid-media": "marketing",
    "ppc": "marketing",
    "brand-strategy": "marketing",
    "brand-management": "marketing",
    "go-to-market": "marketing",
    "product-launch": "marketing",
    "public-relations": "marketing",
    "media-relations": "marketing",
    "lead-generation": "marketing",
    "conversion-optimization": "marketing",
    "cro": "marketing",
    "a/b-testing": "marketing",
    "marketing-analytics": "marketing",
    "marketing-automation": "marketing",
    "campaign-management": "marketing",
    "content-strategy": "marketing",
    "market-research": "marketing",
    "competitive-analysis": "marketing",
    # ── Sales ─────────────────────────────────────────────────────────────
    "b2b-sales": "sales",
    "b2c-sales": "sales",
    "enterprise-sales": "sales",
    "saas-sales": "sales",
    "solution-selling": "sales",
    "consultative-selling": "sales",
    "inbound-sales": "sales",
    "outbound-sales": "sales",
    "sales-development": "sales",
    "account-executive": "sales",
    "account-management": "sales",
    "key-account-management": "sales",
    "customer-success": "sales",
    "sales-strategy": "sales",
    "sales-operations": "sales",
    "sales-enablement": "sales",
    "sales-training": "sales",
    "salesforce": "sales",
    "crm": "sales",
    "territory-management": "sales",
    "inside-sales": "sales",
    "field-sales": "sales",
    "retail-sales": "sales",
    "direct-sales": "sales",
    "cold-calling": "sales",
    "proposal-writing": "sales",
    "sales-presentation": "sales",
    "demo": "sales",
    # ── Finance ───────────────────────────────────────────────────────────
    "accounting": "finance",
    "bookkeeping": "finance",
    "financial-reporting": "finance",
    "financial-analysis": "finance",
    "financial-planning": "finance",
    "budgeting": "finance",
    "forecasting": "finance",
    "tax-preparation": "finance",
    "tax-planning": "finance",
    "audit": "finance",
    "internal-audit": "finance",
    "corporate-finance": "finance",
    "investment-banking": "finance",
    "private-equity": "finance",
    "venture-capital": "finance",
    "angel-investing": "finance",
    "asset-management": "finance",
    "wealth-management": "finance",
    "portfolio-management": "finance",
    "financial-modeling": "finance",
    "valuation": "finance",
    "due-diligence": "finance",
    "treasury": "finance",
    "insurance": "finance",
    "underwriting": "finance",
    "credit-analysis": "finance",
    "lending": "finance",
    "payroll": "finance",
    "cpa": "finance",
    "cfa": "finance",
    # ── Legal ─────────────────────────────────────────────────────────────
    "corporate-law": "legal",
    "contract-law": "legal",
    "intellectual-property": "legal",
    "patent-law": "legal",
    "trademark-law": "legal",
    "copyright-law": "legal",
    "employment-law": "legal",
    "litigation": "legal",
    "arbitration": "legal",
    "mediation": "legal",
    "legal-research": "legal",
    "legal-writing": "legal",
    "legal-compliance": "legal",
    "data-privacy": "legal",
    "regulatory-affairs": "legal",
    "paralegal": "legal",
    "estate-planning": "legal",
    "immigration-law": "legal",
    "contract-negotiation": "legal",
    "corporate-governance": "legal",
    # ── Healthcare ────────────────────────────────────────────────────────
    "medicine": "healthcare",
    "nursing": "healthcare",
    "registered-nurse": "healthcare",
    "physician": "healthcare",
    "surgery": "healthcare",
    "pediatrics": "healthcare",
    "cardiology": "healthcare",
    "neurology": "healthcare",
    "oncology": "healthcare",
    "dermatology": "healthcare",
    "psychiatry": "healthcare",
    "psychology": "healthcare",
    "physical-therapy": "healthcare",
    "occupational-therapy": "healthcare",
    "speech-therapy": "healthcare",
    "radiology": "healthcare",
    "pathology": "healthcare",
    "emergency-medicine": "healthcare",
    "public-health": "healthcare",
    "epidemiology": "healthcare",
    "health-administration": "healthcare",
    "medical-coding": "healthcare",
    "medical-billing": "healthcare",
    "pharmacy": "healthcare",
    "clinical-research": "healthcare",
    "telemedicine": "healthcare",
    "mental-health": "healthcare",
    "nutrition": "healthcare",
    "fitness-training": "healthcare",
    "personal-trainer": "healthcare",
    "holistic-health": "healthcare",
    # ── Education ─────────────────────────────────────────────────────────
    "teaching": "education",
    "instruction": "education",
    "curriculum-development": "education",
    "lesson-planning": "education",
    "educational-assessment": "education",
    "tutoring": "education",
    "mentoring": "education",
    "academic-advising": "education",
    "educational-leadership": "education",
    "edtech": "education",
    "e-learning": "education",
    "instructional-design": "education",
    "online-learning": "education",
    "special-education": "education",
    "early-childhood-education": "education",
    "higher-education": "education",
    "university-teaching": "education",
    "esl": "education",
    "tesol": "education",
    "vocational-training": "education",
    "career-counseling": "education",
    # ── Engineering (non-software) ─────────────────────────────────────────
    "mechanical-engineering": "engineering",
    "electrical-engineering": "engineering",
    "civil-engineering": "engineering",
    "chemical-engineering": "engineering",
    "industrial-engineering": "engineering",
    "aerospace-engineering": "engineering",
    "automotive-engineering": "engineering",
    "biomedical-engineering": "engineering",
    "environmental-engineering": "engineering",
    "structural-engineering": "engineering",
    "materials-engineering": "engineering",
    "cad": "engineering",
    "autocad": "engineering",
    "solidworks": "engineering",
    "catia": "engineering",
    "ansys": "engineering",
    "matlab": "engineering",
    "plc-programming": "engineering",
    "scada": "engineering",
    "hvac-design": "engineering",
    "circuit-design": "engineering",
    "pcb-design": "engineering",
    "embedded-systems": "engineering",
    "firmware": "engineering",
    "fpga": "engineering",
    "structural-analysis": "engineering",
    "thermodynamics": "engineering",
    "fluid-mechanics": "engineering",
    "control-systems": "engineering",
    "surveying": "engineering",
    # ── Manufacturing & Trades ────────────────────────────────────────────
    "cnc-machining": "manufacturing",
    "machining": "manufacturing",
    "welding": "manufacturing",
    "mig-welding": "manufacturing",
    "tig-welding": "manufacturing",
    "soldering": "manufacturing",
    "injection-molding": "manufacturing",
    "3d-printing": "manufacturing",
    "additive-manufacturing": "manufacturing",
    "sheet-metal": "manufacturing",
    "assembly": "manufacturing",
    "production-line": "manufacturing",
    "lean-manufacturing": "manufacturing",
    "six-sigma": "manufacturing",
    "quality-control": "manufacturing",
    "quality-assurance": "manufacturing",
    "iso": "manufacturing",
    "gmp": "manufacturing",
    "process-improvement": "manufacturing",
    # ── Skilled Trades ────────────────────────────────────────────────────
    "plumbing": "trades",
    "pipefitting": "trades",
    "electrical": "trades",
    "electrician": "trades",
    "wiring": "trades",
    "hvac": "trades",
    "carpentry": "trades",
    "woodworking": "trades",
    "framing": "trades",
    "finish-carpentry": "trades",
    "cabinetry": "trades",
    "drywall": "trades",
    "painting": "trades",
    "tiling": "trades",
    "flooring": "trades",
    "roofing": "trades",
    "masonry": "trades",
    "bricklaying": "trades",
    "concrete": "trades",
    "insulation": "trades",
    "glazing": "trades",
    "landscaping": "trades",
    "hardscaping": "trades",
    "pest-control": "trades",
    "locksmith": "trades",
    # ── Agriculture ───────────────────────────────────────────────────────
    "farming": "agriculture",
    "crop-management": "agriculture",
    "agronomy": "agriculture",
    "horticulture": "agriculture",
    "greenhouse": "agriculture",
    "hydroponics": "agriculture",
    "irrigation": "agriculture",
    "organic-farming": "agriculture",
    "livestock": "agriculture",
    "animal-husbandry": "agriculture",
    "dairy-farming": "agriculture",
    "beekeeping": "agriculture",
    "aquaculture": "agriculture",
    "precision-agriculture": "agriculture",
    "farm-management": "agriculture",
    "soil-science": "agriculture",
    "sustainable-agriculture": "agriculture",
    # ── Energy ────────────────────────────────────────────────────────────
    "solar-energy": "energy",
    "solar-installation": "energy",
    "wind-energy": "energy",
    "wind-turbine": "energy",
    "hydroelectric": "energy",
    "geothermal": "energy",
    "nuclear-energy": "energy",
    "oil-and-gas": "energy",
    "petroleum": "energy",
    "energy-storage": "energy",
    "battery-technology": "energy",
    "smart-grid": "energy",
    "power-systems": "energy",
    "power-generation": "energy",
    "renewable-energy": "energy",
    "clean-energy": "energy",
    "energy-efficiency": "energy",
    "carbon-footprint": "energy",
    "climate-tech": "energy",
    # ── Transportation & Logistics ────────────────────────────────────────
    "trucking": "transportation",
    "freight": "transportation",
    "warehousing": "transportation",
    "distribution": "transportation",
    "fleet-management": "transportation",
    "route-optimization": "transportation",
    "shipping": "transportation",
    "logistics": "transportation",
    "cold-chain": "transportation",
    "air-freight": "transportation",
    "ocean-freight": "transportation",
    "courier": "transportation",
    "last-mile-delivery": "transportation",
    "public-transit": "transportation",
    "customs": "transportation",
    "import-export": "transportation",
    "freight-forwarding": "transportation",
    # ── Real Estate ───────────────────────────────────────────────────────
    "real-estate": "real-estate",
    "real-estate-agent": "real-estate",
    "property-management": "real-estate",
    "commercial-real-estate": "real-estate",
    "real-estate-investment": "real-estate",
    "property-development": "real-estate",
    "mortgage": "real-estate",
    "mortgage-brokerage": "real-estate",
    "appraisal": "real-estate",
    "home-inspection": "real-estate",
    "title-search": "real-estate",
    "escrow": "real-estate",
    "leasing": "real-estate",
    "property-valuation": "real-estate",
    "facility-management": "real-estate",
    "proptech": "real-estate",
    # ── Hospitality & Tourism ─────────────────────────────────────────────
    "hotel-management": "hospitality",
    "hospitality": "hospitality",
    "front-desk": "hospitality",
    "concierge": "hospitality",
    "housekeeping": "hospitality",
    "restaurant-management": "hospitality",
    "catering": "hospitality",
    "banquet": "hospitality",
    "event-planning": "hospitality",
    "wedding-planning": "hospitality",
    "bar-management": "hospitality",
    "bartending": "hospitality",
    "mixology": "hospitality",
    "barista": "hospitality",
    "culinary": "hospitality",
    "cooking": "hospitality",
    "chef": "hospitality",
    "pastry": "hospitality",
    "baking": "hospitality",
    "food-safety": "hospitality",
    "menu-planning": "hospitality",
    "travel-agency": "hospitality",
    "tour-guide": "hospitality",
    # ── Science & Research ────────────────────────────────────────────────
    "physics": "science",
    "chemistry": "science",
    "biology": "science",
    "biochemistry": "science",
    "genetics": "science",
    "microbiology": "science",
    "immunology": "science",
    "neuroscience": "science",
    "geology": "science",
    "astronomy": "science",
    "mathematics": "science",
    "statistics": "science",
    "spectroscopy": "science",
    "microscopy": "science",
    "lab-management": "science",
    "bioinformatics": "science",
    "crispr": "science",
    # ── Military & Defense ────────────────────────────────────────────────
    "command": "military",
    "tactical-operations": "military",
    "combat": "military",
    "naval-operations": "military",
    "military-aviation": "military",
    "cyber-warfare": "military",
    "intelligence": "military",
    "reconnaissance": "military",
    "military-logistics": "military",
    "military-training": "military",
    "military-medicine": "military",
    "veteran-affairs": "military",
    "security-cleared": "military",
    # ── Sports & Fitness ──────────────────────────────────────────────────
    "coaching": "sports",
    "athletic-training": "sports",
    "strength-conditioning": "sports",
    "sports-performance": "sports",
    "sports-psychology": "sports",
    "sports-nutrition": "sports",
    "sports-medicine": "sports",
    "physical-education": "sports",
    "group-fitness": "sports",
    "yoga": "sports",
    "martial-arts": "sports",
    "sports-management": "sports",
    "athletic-director": "sports",
    "sports-marketing": "sports",
    "sports-analytics": "sports",
    "scouting": "sports",
    "refereeing": "sports",
    "e-sports": "sports",
    # ── Arts & Entertainment ──────────────────────────────────────────────
    "painting": "arts",
    "sculpture": "arts",
    "ceramics": "arts",
    "pottery": "arts",
    "printmaking": "arts",
    "art-history": "arts",
    "art-curation": "arts",
    "gallery-management": "arts",
    "art-restoration": "arts",
    "jewelry-making": "arts",
    "textiles": "arts",
    # ── Performing Arts ───────────────────────────────────────────────────
    "acting": "performing-arts",
    "theater": "performing-arts",
    "stage-acting": "performing-arts",
    "film-acting": "performing-arts",
    "voice-acting": "performing-arts",
    "directing": "performing-arts",
    "choreography": "performing-arts",
    "dance": "performing-arts",
    "playwriting": "performing-arts",
    "stage-management": "performing-arts",
    "set-design": "performing-arts",
    "lighting-design": "performing-arts",
    "musical-theater": "performing-arts",
    # ── Media & Journalism ────────────────────────────────────────────────
    "journalism": "media-journalism",
    "reporting": "media-journalism",
    "investigative-journalism": "media-journalism",
    "broadcast-journalism": "media-journalism",
    "photo-journalism": "media-journalism",
    "data-journalism": "media-journalism",
    "copy-editing": "media-journalism",
    "news-production": "media-journalism",
    "podcast-production": "media-journalism",
    "radio": "media-journalism",
    "television": "media-journalism",
    "cinematography": "media-journalism",
    "documentary": "media-journalism",
    "media-strategy": "media-journalism",
    # ── Community & Social Good ───────────────────────────────────────────
    "social-work": "community-social",
    "community-organizing": "community-social",
    "community-development": "community-social",
    "advocacy": "community-social",
    "human-rights": "community-social",
    "fundraising": "community-social",
    "grant-writing": "community-social",
    "volunteer-management": "community-social",
    "nonprofit-management": "community-social",
    "public-policy": "community-social",
    "crisis-intervention": "community-social",
    "youth-development": "community-social",
    "diversity-equity-inclusion": "community-social",
    "conflict-resolution": "community-social",
    "international-development": "community-social",
    # ── General / Cross-domain ────────────────────────────────────────────
    "research": "general",
    "analysis": "general",
    "critical-thinking": "general",
    "problem-solving": "general",
    "communication": "general",
    "written-communication": "general",
    "verbal-communication": "general",
    "interpersonal-skills": "general",
    "teamwork": "general",
    "collaboration": "general",
    "time-management": "general",
    "organization": "general",
    "adaptability": "general",
    "creativity": "general",
    "emotional-intelligence": "general",
    "resilience": "general",
    "continuous-learning": "general",
    "attention-to-detail": "general",
    "multitasking": "general",
    "delegation": "general",
    "customer-service": "general",
    "client-service": "general",
    "networking": "general",
    "bilingual": "general",
    "multilingual": "general",
    "language-skills": "general",
}

CATEGORY_NAMES: dict[str, str] = {
    "frontend": "Frontend Development",
    "backend": "Backend Development",
    "database": "Database Engineering",
    "devops": "DevOps & Infrastructure",
    "cloud": "Cloud Computing",
    "ai-ml": "AI & Machine Learning",
    "security": "Cybersecurity",
    "mobile": "Mobile Development",
    "design": "Design & UX",
    "creative": "Creative & Content",
    "business": "Business & Management",
    "marketing": "Marketing",
    "sales": "Sales",
    "finance": "Finance & Accounting",
    "legal": "Legal & Compliance",
    "healthcare": "Healthcare & Medicine",
    "education": "Education & Teaching",
    "engineering": "Engineering (Non-Software)",
    "manufacturing": "Manufacturing & Production",
    "trades": "Skilled Trades",
    "agriculture": "Agriculture & Farming",
    "energy": "Energy & Utilities",
    "transportation": "Transportation & Logistics",
    "real-estate": "Real Estate & Property",
    "hospitality": "Hospitality & Tourism",
    "science": "Science & Research",
    "military": "Military & Defense",
    "sports": "Sports & Fitness",
    "arts": "Arts & Visual Culture",
    "performing-arts": "Performing Arts",
    "media-journalism": "Media & Journalism",
    "community-social": "Community & Social Impact",
    "general": "General Professional Skills",
}


def get_skill_category(skill_name: str) -> str:
    """Return the category for a skill name, defaulting to 'general'.

    Args:
        skill_name: A skill name like 'react', 'python', 'welding'.

    Returns:
        The normalized category string, e.g. 'frontend', 'backend', 'trades'.
        Returns 'general' if the skill is not in the mapping.
    """
    return SKILL_CATEGORIES.get(skill_name.lower().strip(), "general")
